version: '3.8'
services:
  redis:
    image: "redis:6.2-alpine"
    container_name: "redis"
    restart: unless-stopped
    expose:
      - "6379"
    command: redis-server --save 60 5
    volumes:
      - ./cache:/data
  server:
    image: yt_thumbnails_server
    container_name: yt_thumbnails_server
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis