// Code generated by mockery v2.14.0. DO NOT EDIT.

package clientmock

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "thumbs/proto"
)

// ThumbClient is an autogenerated mock type for the ThumbClient type
type ThumbClient struct {
	mock.Mock
}

// GetThumbnail provides a mock function with given fields: ctx, in, opts
func (_m *ThumbClient) GetThumbnail(ctx context.Context, in *pb.ThumbRequest, opts ...grpc.CallOption) (*pb.ThumbResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.ThumbResponse
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ThumbRequest, ...grpc.CallOption) *pb.ThumbResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ThumbResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.ThumbRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewThumbClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewThumbClient creates a new instance of ThumbClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewThumbClient(t mockConstructorTestingTNewThumbClient) *ThumbClient {
	mock := &ThumbClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
