// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: thumbnails.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ThumbClient is the client API for Thumb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThumbClient interface {
	GetThumbnail(ctx context.Context, in *ThumbRequest, opts ...grpc.CallOption) (*ThumbResponse, error)
}

type thumbClient struct {
	cc grpc.ClientConnInterface
}

func NewThumbClient(cc grpc.ClientConnInterface) ThumbClient {
	return &thumbClient{cc}
}

func (c *thumbClient) GetThumbnail(ctx context.Context, in *ThumbRequest, opts ...grpc.CallOption) (*ThumbResponse, error) {
	out := new(ThumbResponse)
	err := c.cc.Invoke(ctx, "/pb.Thumb/GetThumbnail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThumbServer is the server API for Thumb service.
// All implementations must embed UnimplementedThumbServer
// for forward compatibility
type ThumbServer interface {
	GetThumbnail(context.Context, *ThumbRequest) (*ThumbResponse, error)
	mustEmbedUnimplementedThumbServer()
}

// UnimplementedThumbServer must be embedded to have forward compatible implementations.
type UnimplementedThumbServer struct {
}

func (UnimplementedThumbServer) GetThumbnail(context.Context, *ThumbRequest) (*ThumbResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbnail not implemented")
}
func (UnimplementedThumbServer) mustEmbedUnimplementedThumbServer() {}

// UnsafeThumbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThumbServer will
// result in compilation errors.
type UnsafeThumbServer interface {
	mustEmbedUnimplementedThumbServer()
}

func RegisterThumbServer(s grpc.ServiceRegistrar, srv ThumbServer) {
	s.RegisterService(&Thumb_ServiceDesc, srv)
}

func _Thumb_GetThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbServer).GetThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Thumb/GetThumbnail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbServer).GetThumbnail(ctx, req.(*ThumbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Thumb_ServiceDesc is the grpc.ServiceDesc for Thumb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Thumb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Thumb",
	HandlerType: (*ThumbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThumbnail",
			Handler:    _Thumb_GetThumbnail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thumbnails.proto",
}
